name: Nicolas P Contomichalos
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5772832217626274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced3cf'
    - '#1a0b08'
    - '#a6a590'
    - '#564a4c'
    - '#e57206'
  brandStrength: 0.5625
  lightness: 0.8848034930415452
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
